# Generated by Django 2.2 on 2020-01-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupcrawling',
            name='content',
        ),
    ]
