# Generated by Django 2.2 on 2020-01-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_meetupcrawling_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devevent',
            name='source',
            field=models.CharField(choices=[('manual', '직접 입력'), ('user', '사용자 요청'), ('festa', 'FESTA 크롤링'), ('meetup', 'MEETUP 크롤링'), ('eventus', 'EVENTUS 크롤링'), ('facebook', 'FACEBOOK 크롤링')], default='user', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventuscrawling',
            name='source',
            field=models.CharField(choices=[('manual', '직접 입력'), ('user', '사용자 요청'), ('festa', 'FESTA 크롤링'), ('meetup', 'MEETUP 크롤링'), ('eventus', 'EVENTUS 크롤링'), ('facebook', 'FACEBOOK 크롤링')], default='eventus', max_length=30),
        ),
        migrations.AlterField(
            model_name='facebookcrawling',
            name='source',
            field=models.CharField(choices=[('manual', '직접 입력'), ('user', '사용자 요청'), ('festa', 'FESTA 크롤링'), ('meetup', 'MEETUP 크롤링'), ('eventus', 'EVENTUS 크롤링'), ('facebook', 'FACEBOOK 크롤링')], default='facebook', max_length=30),
        ),
        migrations.AlterField(
            model_name='festacrawling',
            name='source',
            field=models.CharField(choices=[('manual', '직접 입력'), ('user', '사용자 요청'), ('festa', 'FESTA 크롤링'), ('meetup', 'MEETUP 크롤링'), ('eventus', 'EVENTUS 크롤링'), ('facebook', 'FACEBOOK 크롤링')], default='festa', max_length=30),
        ),
        migrations.AlterField(
            model_name='manualevent',
            name='source',
            field=models.CharField(choices=[('manual', '직접 입력'), ('user', '사용자 요청'), ('festa', 'FESTA 크롤링'), ('meetup', 'MEETUP 크롤링'), ('eventus', 'EVENTUS 크롤링'), ('facebook', 'FACEBOOK 크롤링')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='meetupcrawling',
            name='source',
            field=models.CharField(choices=[('manual', '직접 입력'), ('user', '사용자 요청'), ('festa', 'FESTA 크롤링'), ('meetup', 'MEETUP 크롤링'), ('eventus', 'EVENTUS 크롤링'), ('facebook', 'FACEBOOK 크롤링')], default='meetup', max_length=30),
        ),
        migrations.AlterField(
            model_name='notdevevent',
            name='source',
            field=models.CharField(choices=[('manual', '직접 입력'), ('user', '사용자 요청'), ('festa', 'FESTA 크롤링'), ('meetup', 'MEETUP 크롤링'), ('eventus', 'EVENTUS 크롤링'), ('facebook', 'FACEBOOK 크롤링')], default='user', max_length=30),
        ),
        migrations.AlterField(
            model_name='userrequestevent',
            name='source',
            field=models.CharField(choices=[('manual', '직접 입력'), ('user', '사용자 요청'), ('festa', 'FESTA 크롤링'), ('meetup', 'MEETUP 크롤링'), ('eventus', 'EVENTUS 크롤링'), ('facebook', 'FACEBOOK 크롤링')], default='user', max_length=30),
        ),
        migrations.AlterField(
            model_name='waitingevent',
            name='source',
            field=models.CharField(choices=[('manual', '직접 입력'), ('user', '사용자 요청'), ('festa', 'FESTA 크롤링'), ('meetup', 'MEETUP 크롤링'), ('eventus', 'EVENTUS 크롤링'), ('facebook', 'FACEBOOK 크롤링')], default='facebook', max_length=30),
        ),
    ]
